### ISSUE TITLE
sub/util is outdated

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-coord#201]
sub/util is pointing to an older release.

**Comment by juagargi** [comment]
PR #202

**Comment by hausheer** [comment]
thnx, would it make sense to point sub/util always to the latest version?

**Comment by juagargi** [comment]
Probably yes, but I don't think we can do that with git submodules.
Another workflow we could follow is to keep util at the version we need for the coordinator, and only update it if we need something newer. This way we care about the breaking changes introduced in util only if we need to update it because something cool that we need was added.
What do you think?

**Comment by juagargi** [comment]
Git submodules can track a branch:
https://stackoverflow.com/a/18797720/817736

We are tracking now "master" . To update:
git submodule update --remote
