### ISSUE TITLE
Redirect http, https aliases to https://www.scionlab.org

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-coord#203]
We are using caddy at this moment. We redirect successfully http, but it looks like e.g. https://coord.scionlab.org is not well redirected to https://www.scionlab.org
We might need to include these other names in the HTTPS certificate for the server.

**Comment by xabarass** [comment]
I think we'll have to explicitly list all those https domains that we want to redirect from so that they can obtain valid certificates. As far as I understand, if the user explicitly types https in url and DNS leads him to our server we have to respond to that with a valid https redirect.
I've added https://coord.scionlab.org and https://coord.scionproto.net to redirect https traffic. Should be working now.

**Comment by hausheer** [comment]
Great, thanks @xabarass! Could you add https://scionlab.org and https://scion-ad6.inf.ethz.ch/ as well?

**Comment by xabarass** [comment]
Done!
