### ISSUE TITLE
[SCIONLab] Mechanism to update code and configuration for VMs

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-coord#83]
There should be a mechanism to update the SCION code and VM configuration for all SCIONLab VMs without requiring interaction by the users.

**Comment by mlegner** [comment]
@xabarass Would you be interested to take over this issue, as you have been working on the install script etc. already?

**Comment by xabarass** [comment]
Yes sure, I can do this.
Is running update script as a cron job appropriate solution? Every host could create daily cron job at a random time, to avoid everybody updating at same time, and restart SCION if necessary?

**Comment by mlegner** [comment]
Yes, that sounds like a good idea. We could also use systemd timers, those alow to randomize the time in a defined range (https://www.freedesktop.org/software/systemd/man/systemd.timer.html).
The question would be, if we also want to query the coordination service for updates, but I think that would be part of #109.

**Comment by xabarass** [comment]
Sysd timers look like a cleaner solution. I will implement it that way.

**Comment by hausheer** [comment]
In general I like the auto-update feature. One thing to keep in mind are SCION updates that may break the communication (e.g. header format changes). Ideally, these should happen synchronously to minimize downtimes. In the past we discussed as an additional option to deal with the update problem a "flag" that can be set on the SCION coordinator (e.g. by an admin or by an eligible user) that marks a SCION node for update (similar to the "reinstall" flag in PlanetLab). What if we introduce on the coordinator a flag with the following states for each node:
- random_auto_update (default): the node will automatically update at a random time whenever a new release is available
- sync_update <time>: the node is scheduled for a synchronized update at a particular time (an admin could choose to set this status to trigger an update, afterwards the node will be set back to random_auto_update)
- manual_update: the node will not be updated automatically (this could be useful in case a user made custom changes to the code and will update the node manually)
- reinstall: the node will be reinstalled completely (this could be useful in case an update fails)

**Comment by mlegner** [comment]
Good point, @hausheer.
If we indeed use systemd timers, we can use the feature `RandomizedDelaySec` such that the update is not completely random but within some interval at the same time each day. In that case, we maybe don't have to distinguish between the first two options.
The other two options could be documented on the tutorials page:

- manual_update: Simply disable the timer and run the update script by hand.
- reinstall: Download an updated configuration from the coordinator and then call `vagrant destroy` and `vagrant up` again.

What do you think?

**Comment by hausheer** [comment]
@mlegner As for the VMs this sounds like a good approach for now. 

For the PC engines etc. we may need more than that but that goes probably beyond this issue here.

**Comment by xabarass** [comment]
Regarding the update procedure.

I made a small [script](https://gist.github.com/xabarass/afc38b58bf4476c4ef4379b7a973cbc4) that will handle actual update (wrapper around git rebase). Idea is to use systemd timers and invoke this script when configured. If user want's to run script manually he can just disable systemd service.

There are still few things I would like to discuss:
- Where should we keep this script? My idea is to keep it in scion repository and extend scion.sh to accept argument "update" so running `./scion.sh update` will handle everything.
- How to handle situations where automatic update is not possible because of user's modifications or uncommited files? If user modifies some files automatic rebase won't work and it will require manual actions. My idea is to create web service on scion-coord where update script can report failure and we can notify user with email to fix his repository.

**Comment by perrig** [comment]
Hi Milan,

Changes to the scion.sh script should be discussed with the dev team. Maybe
we can go have lunch with them one of these days and discuss it with them
(Friday would work for me).

All the best,
  Adrian

**Comment by mlegner** [comment]
This issue is partially addressed in #162.

**Comment by mlegner** [comment]
This has been fixed by multiple PRs in the meantime.
